name: Python

on: 
  workflow_dispatch:
    branches: [main]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
          python-version: 3.11 #install the python needed
    - name: run python file
      run: python beetle_function.py
